---
title: "Lab Rotation Report"
author: "Vera Götz"
date: "`r Sys.Date()`"
mainfont: "Calibri"
header-includes:
  - \renewcommand{\arraystretch}{1.5}
output:
  pdf_document:
    toc: true
    number_sections: true
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
```

# Introduction

# Materials and Methods

## Reagents

```{r reagents-table}
reagents <- data.frame(
  Name = c("D(+)-Saccharose", "Dimethyl sulfoxide", "Acetone, Glas Distilled"),
  'Article Number' = c("4621.1", "34869-500ML", "10015" ),
  Company = c("Carl ROTH", "Sigma-Aldrich", "Electron Microscopy Sciences"),
  check.names = FALSE
)

kable(reagents, booktabs = TRUE) %>%
  kable_styling(full_width = TRUE) %>%
  column_spec(1:3, width = "5.08cm")
```


## Buffers and Solutions

```{r buffers-table}
buffers <- data.frame(
  Name = c("Cryopreservation solution"),
  Composition = c("5% Me2SO (v/v), 0.1% sucrose (w/v)")
)

kable(buffers, booktabs = TRUE) %>%
  kable_styling(full_width = TRUE) %>%
  column_spec(1, width = "6.8cm") %>%
  column_spec(2, width = "8.8cm")
```

## Tools and Devices

```{r tools-table}
tools <- data.frame(
  `Tool/Device` = c("High Pressure Freezer", "Automatic Freeze Substitution System", "MicroCT", "Ultramicrotome", "Pipette controller", "Syringe (1mL)", "Tube Assemblies for Pipettes", "Microcapillary tubes/Microcaps®", "Cell Strainer (40µm)", "Screw Top Microcentrifuge Tubes (2mL)", "Modeling wax"),
  Model = c("HPM 010", "EM AFS II", "SkyScan 1272", "EM UC7", "micro-classic", "Omnifix® 40 Solo", "A5177-5EA", "P1924-1PAK", "431750", "HS10060", ""),
  Company = c("BAL-TEC", "Leica", "Bruker", "Leica","BRAND", "B. Braun SE", "Merck", "Drummond", "Corning", "Heathrow Scientific", "Sallinger GmbH (MORSA)"),
  check.names = FALSE
)

kable(tools, booktabs = TRUE) %>%
  kable_styling(full_width = TRUE) %>%
  column_spec(1:3, width = "5.08cm")
```

# Results

# Discussion
